name: rl-workshop
channels:
  - conda-forge
  - pytorch
dependencies:
- python=3.6
- pytorch=1.3
- torchvision=0.4
- scikit-learn=0.21
- jupyterlab=1.1
- numpy=1.17
- pandas=0.25
- matplotlib=3.0
- seaborn=0.9.0
- ipywidgets
- nodejs
- tqdm==4.41.1
- pillow=7.0.0
- pip
- pip:
  - gym==0.15.3
